on:
    push:
    workflow_dispatch:
    schedule:
        - cron:  '*/10 * * * *'

permissions: write-all

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
            - run: python start.py > data.json
            - run: |-
                  git config user.name 'GitHub Actions'
                  git config user.email 'actions@users.noreply.github.com'
                  git add -A
                  git commit -m 'Updates' || exit 0
                  git push
